// Fill out your copyright notice in the Description page of Project Settings.


#include "BuildingBase.h"
#include "../MyGamePlayerState.h"
#include "BuildingProductionComponent.h"
#include "../Character/GameCharacterBase.h"
#include "BuildingStruct.h"
#include "../Status/StatusComponent.h"

// Sets default values
ABuildingBase::ABuildingBase()
{
 	PrimaryActorTick.bCanEverTick = false;

	Root = CreateDefaultSubobject<USceneComponent>(TEXT("Root Component"));
	SetRootComponent(Root);
	DefaultMesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("DefaultMesh"));
	DefaultMesh->SetupAttachment(Root);

	Mesh = CreateDefaultSubobject<UStaticMeshComponent>(TEXT("Mesh"));
	Mesh->SetupAttachment(DefaultMesh);
	Mesh->SetVisibility(false);

	// РЬЛѕГЂ ОШКИРг..
	Boxcollision = CreateDefaultSubobject<UBoxComponent>(TEXT("BoxCollusion"));
	Boxcollision->SetupAttachment(DefaultMesh);
	Boxcollision->SetVisibility(true);
	Boxcollision->SetHiddenInGame(false);
	Boxcollision->SetGenerateOverlapEvents(true);
	Boxcollision->SetCollisionProfileName(TEXT("Trigger")); //ПРЙіЗІ УЄГЮ ИИЕщОюОпЧвЕэ.

	StatusComp = CreateDefaultSubobject<UStatusComponent>(TEXT("StatusComp"));
	// АЧЙА БтКЛ : HP / ЛчИСИИ ЛчПы ->InitFromBaseStatПЁ СжРд

	// РкПј МіБоПы РкНФПЁМ­ ВШБт
	//ProductionComp = CreateDefaultSubobject<UBuildingProductionComponent>(TEXT("ProductionComp"))
}

// Called when the game starts or when spawned
void ABuildingBase::BeginPlay()
{
	Super::BeginPlay();
	UStaticMesh* MeshAsset = Cast<UStaticMesh>(StaticLoadObject(UStaticMesh::StaticClass(), nullptr, TEXT("/Game/Building/Mesh/Laboratory/SubBuilding/SM_Laboratory_Workplace.SM_Laboratory_Workplace")));
	if (MeshAsset)
		DefaultMesh->SetStaticMesh(MeshAsset);
	InitBuilding();
}


const FBuildingLevelData* ABuildingBase::GetRow(int32 InLevel) const
{
	UE_LOG(LogTemp, Warning, TEXT("In GetRow"));

	const FName RowName(*FString::FromInt(InLevel));
	UE_LOG(LogTemp, Warning, TEXT("get data by level :  %d"),InLevel);
	const FBuildingLevelData* Row = DataTableAsset->FindRow<FBuildingLevelData>(RowName, TEXT("GetRow"));
	if (!Row)
	{
		UE_LOG(LogTemp, Warning, TEXT("[%s] No Row for Level %d"), *GetName(), InLevel);
	}
	return Row;
}

void ABuildingBase::ApplyRow(const FBuildingLevelData& Row)
{
	//ЧЎЧЧРЏТЁЄЗ 
    StatusComp->SetBaseStat(Row.BuildingStat, true);
	
	UpdateVisualForLevel(Row.meshRef);
	overlapoffset = Row.ovelapOffset;
	Boxcollision->SetBoxExtent(Boxcollision->GetScaledBoxExtent() + FVector(overlapoffset,overlapoffset, 0.f));
	
	PostApplyRow();
	//ШПАњ ЙпЕП. ФФЦїГЭЦЎПЁ НХШЃСжБт?
	ProductionComp->InitBuildingEffect(Row);

}

void ABuildingBase::UpdateVisualForLevel(const FString& Ref)
{
	if (Ref.IsEmpty())
	{
		UE_LOG(LogTemp, Warning, TEXT("MeshRef not set"));
		return;
	}
	
	UStaticMesh* MeshAsset = Cast<UStaticMesh>(StaticLoadObject(UStaticMesh::StaticClass(),nullptr,*Ref));

	if (MeshAsset)
	{
		Mesh->SetStaticMesh(MeshAsset);
		if (CurrentLevel > 0) 
		{
			FBoxSphereBounds bound = Mesh->GetStaticMesh()->GetBounds();
			Boxcollision->SetWorldLocation(bound.Origin +GetActorLocation());
			Boxcollision->SetBoxExtent(bound.BoxExtent + FVector(overlapoffset, overlapoffset, 0.f));
		}
	}
}

void ABuildingBase::OnReceiveAnyDamage(float Amount)
{
	StatusComp->TakeDamage(Amount);
}

void ABuildingBase::OnBuildingDied(AActor* DeadOwner) // isDeadЗЮ КЏАц ЧиОпЧд
//СіБн ВЋ ОЦИЖ ДйИЅОжАЁ СзОњРЛЖЇ ШПАњ СІОюЧЯЗСАэ ЧбЕэ.
{
	bIsDestroyed = true;

	// УцЕЙ/ХИАйЦУ КёШАМКШ­
	SetActorEnableCollision(false);

	// МіБо СпСі
	//if (ProductionComp) ProductionComp->ClearBySource(this);

	// ИоНУ БГУМ/РЬЦхЦЎ/ЛчПюЕх

	// ЧЪПфЧЯДйИщ, АдРг НУНКХлПЁ ОЫИВ(НКХзРЬСі НЧЦа ЦЎИЎАХ Ею)
	// OnBuildingDestroyed.Broadcast(this);

	// КєЕљ НКХзРЬЦЎ ФФЦїГЭЦЎПЁ ЕЅРЬХЭ РќМл.
	ProductionComp->OnExplosion();

	Destroy();
}

void ABuildingBase::SetDataTable(FString path)
{
	if (!path.IsEmpty())
	{
		UObject* dt = StaticLoadObject(UDataTable::StaticClass(), nullptr, *path);
		if(dt)
			DataTableAsset = Cast<UDataTable>(dt);
		else
			UE_LOG(LogTemp, Warning, TEXT("DataTable Path is Wrong : [%s]"), *path);
	}
	else
		UE_LOG(LogTemp, Warning, TEXT("DataTable Path is Empty : [%s]"), *path);
}

void ABuildingBase::OnInteraction()
{
	// АЧЙА ЛѓШЃРлПы -> ЧУЗЙРЬОю ЧбХз ДјСіБт
	/*ЧУЗЙРЬОюАЁ ПРЙіЗІЧб АЧЙАРЛ РЮНФЧЯАэ ЧУЗЙРЬОюАЁ НХШЃИІ АЧЙАПЁАд СжДТ ЙцНФРИЗЮ ЧиАс*/
	//ЧУЗЙРЬОюАЁ ПРЙіЗІЧЯИщ РЬАХ КЮИЃИщ ЕЩЕэ.
	// UIПЁ ЕЅРЬХЭ СЄКИ ЙкОЦСжБт.

}

void ABuildingBase::InitBuilding()
{
	UE_LOG(LogTemp, Warning, TEXT("In Initbuilding"));
	PreInit();		// ЛѓМгЙоРК ОжЕщПЁМ­ БИЧі
	const FBuildingLevelData* Row = GetRow(CurrentLevel);
	if (Row)
	{
		StatusComp->InitFromBaseStat(Row->BuildingStat, EStatusOwnerType::Building, true);
		ApplyRow(*Row);
	}
	else 
	{
		UE_LOG(LogTemp, Warning, TEXT("LevelData is None!"));
	}
	PostInit();		// ЛѓМгЙоРК ОжЕщПЁМ­ БИЧі.
}

void ABuildingBase::OpenUI()
{
	//UI ЖчПьБт РЬАХ КДПЕРЬЖћ ЛѓСЁ ААРК АцПьПЁДТ ДйИЃБт ЖЇЙЎПЁ АэЙЮЧиКСОпЧвЕэ.
}

bool ABuildingBase::LevelUp()
{
	// ЗЙКЇОїРК РЇСЌПЁМ­ ШЃУтЧЯДТ АЭРИЗЮ.
	UE_LOG(LogTemp, Warning, TEXT("In Levelup"));
	if (!bIsBuilt && CurrentLevel==0)
	{
		Mesh->SetVisibility(true);
	}
	const FBuildingLevelData* Next = GetRow(CurrentLevel + 1);
	if (!Next)
	{
		UE_LOG(LogTemp, Warning, TEXT("[%s] No next level from %d"), *GetName(), CurrentLevel);
		return false;
	}

	CurrentLevel = Next->Level;

	// КЃРЬНК НКХШ БГУМ(HP КёРВ РЏСі)
	StatusComp->SetBaseStat(Next->BuildingStat,true);

	UE_LOG(LogTemp, Warning, TEXT("In ApplyRow"));
	// Лѕ ЗЙКЇ ШПАњ РчЕюЗЯ
	ApplyRow(*Next);

	return true;
}

void ABuildingBase::Preview(bool isPressKey)
{
	if (CurrentLevel > 1) return;

	Mesh->SetVisibility(isPressKey);
}

void ABuildingBase::ImportStageData(int32 lv)
{
	CurrentLevel = lv;
	bIsBuilt = lv > 0 ? true : false;
}

void ABuildingBase::SaveStageData(FString actRef, int32 lv, FVector pos, bool isbuilt)
{
}



