// Fill out your copyright notice in the Description page of Project Settings.


#include "SkillComponent.h"
#include "../Damage/DamageComponent.h"

USkillComponent::USkillComponent()
{
	PrimaryComponentTick.bCanEverTick = true;

}


void USkillComponent::BeginPlay()
{
	Super::BeginPlay();

	m_Skills.Empty();
	m_Size = 0;
	bPlayer = false;

	
}


// Called every frame
void USkillComponent::TickComponent(float DeltaTime, ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction)
{
	Super::TickComponent(DeltaTime, TickType, ThisTickFunction);

	for (USkill* Skill : m_Skills)
	{
		if (!Skill) continue;

		bool bCoolDown = Skill->CoolDown(DeltaTime);

		if (bCoolDown)
		{
			//Ф№ ГЁГЕРЛЖЇ УГИЎ onSkillCoolDownFinished.Broadcast(Slot);
		}
	}

}



//ЧУЗЙРЬОюДТ НУРлРќ bIsPlqyer = true
void USkillComponent::InitSkill(const TArray<FSkillConfig>& SkillSetConfig, int32 Level)
{
	if (bPlayer) m_Skills.SetNum(4);
	else m_Skills.SetNum(3); //КИНКДТ ГЊСпПЁ НКРЇФЁ УГИЎ ЄЁЄЁ

	UDataTable* SkillDataTable = LoadObject<UDataTable>(nullptr, TEXT("/Game/Data/Skill/DT_Table.DT_Table"));
	if (!SkillDataTable)
	{
		UE_LOG(LogTemp, Warning, TEXT("Failed to Load SkillDataTable"));
		return;
	}

	TArray<FSkillData*> AllRows;
	SkillDataTable->GetAllRows(TEXT("SkillInit"), AllRows);

	int32 CurrentIndex = 0;

	for (const FSkillConfig& Config : SkillSetConfig)
	{
		const FString TargetClass = Config.ClassType.ToString(); //"Player","Sword" , "02" -> ЧУЗЙРЬОюХЌЗЁНК АЫЙЋБтХИРдРЧ 2ЙјНКХГ
		const FString WeaponType = Config.WeaponType.ToString();
		int32 SkillCount = Config.Count;

		int32 FoundCount = 0;

		for (FSkillData* Row : AllRows)
		{
			if (!Row) continue;

			if (!Row->SkillID.ToString().StartsWith(TargetClass)) continue;
			if (!Row->WeaponType.ToString().StartsWith(WeaponType)) continue;
			if (FoundCount >= SkillCount) break;

			USkill* NewSkill = NewObject<USkill>(this);
			NewSkill->SetSkillData(*Row);
			NewSkill->SetSkillLevel(Level);

			m_Skills[CurrentIndex++] = NewSkill;

			FoundCount++;
		}
	}

}

void USkillComponent::ApplySkillEffect(USkill* pSkill, AActor* pTarget)
{
	if (!pSkill) return;

	const FSkillData& SkillData = pSkill->GetSkillData();
	const FSkillLevelData SkillLevelData = pSkill->GetSkillLevelData();

	TArray<AActor*> Targets;
	UDamageComponent* DmgComp = GetOwner()->FindComponentByClass<UDamageComponent>();
	if (!DmgComp) return;

	bool bCasterIsPlayer = GetOwner()->ActorHasTag("Player"); //ЧУЗЙРЬОю ФГИЏХЭ КэЗчЧСИАЦЎ ХТБз МГСЄЧиОпЧд
	FSkillTraceParams pTrace;
	pTrace.Range = SkillData.Range + SkillLevelData.AddRange;
	pTrace.HalfHeight = SkillData.HalfHeight + SkillLevelData.AddHalfHeight;
	pTrace.Radius = SkillData.Radius + SkillLevelData.AddRadius;
	pTrace.ConeHalfAngle = 
	pTrace.Channel = ECC_Visibility;

	switch (SkillData.SkillTrigger)
	{
	case ESkillTriggerType::None: //ДыЙЬСі ЦЎИЎАХ  DamageComponent->CollectTarget_Self(pTrace, Targets); break;
		break;
	case ESkillTriggerType::One:
		break;
	case ESkillTriggerType::SelfRadius:
		break;
	case ESkillTriggerType::TargetRadius:
		break;
	case ESkillTriggerType::TargetPoint:
		break;
	}

	for (AActor* Tgt : Targets)
	{
		if (!Tgt) continue;
		UDamageComponent* TgtDmgComp = Tgt->FindComponentByClass<UDamageComponent>();

		//TgtDmgComp->CalcuStatuEffect(SkillLevelData);
		//TgtDmgComp->CalcuCC(SkillLevelData);

		switch (SkillData.SkillType)
		{
		case ESkillType::None:
			break;
		case ESkillType::Attack: //TgtDamageComponent->CalculateDamage(SkillLevelData);
			break;
		case ESkillType::Buff:
			break;
		case ESkillType::DeBuff:
			break;
		case ESkillType::Heal:
			break;
		default:
			break;
		}
	}

}

bool USkillComponent::TryUseSKill(int32 Index)
{
	if (!m_Skills.IsValidIndex(Index)) return false;

	USkill* Skill = m_Skills[Index];
	if (!Skill || !Skill->IsReady()) return false;


	Skill->ExecuteSkill(GetOwner());
	//ЙќРЇСіСЄНУ?  ЧУЗЙРЬОю : РЮХЭЦфРЬНК ШЃУт -> (РЇФЁАЊ) 
	//ОЦБК,РћБК : РЮХЭЦфРЬНК ШЃУт(ХИАй?)
	return true;
}

bool USkillComponent::UpgradeSkill(FName SkillID)
{
	for (USkill* Slot : m_Skills)
		if (Slot && Slot->GetSkillData().SkillID == SkillID)
			return Slot->SkillLevelUp();
	return false;
}


/*
//ОжДЯИоРЬМЧПЁ ГыЦМЦФРЬ СюОюБГПЫЧЯЙЧО№ ЕЧОйЕхРИРП
void UAnimNotify_DoMeleeHit::Notify(USkeletalMeshComponent* MeshComp, UAnimSequenceBase* Anim)
{
	if (AActor* Owner = MeshComp->GetOwner())
		if (USkillComponent* SC = Owner->FindComponentByClass<USkillComponent>())
		{
			// ЧіРч ФГНКЦУ СпРЮ ННЗд/НКХГ ЧкЕщЗЮ ЄЁЄЁЄЁ
			SC->ApplySkillEffect(CurrentCastingSlot, CurrentTarget);
		}
		РЬЗБНФ
}
*/